# Computational Thinking & Coding - Week 2
# Finger Exercises (Lectures 3 & 4)
# Name: Badaila Samir

# ==============================================================================
# LECTURE 3: LOOPS (while, for, range)
# ==============================================================================

# 1. While Loop FE: Summing integers from 1 to N
# Demonstrates while loop condition, counter update, and loop termination
'''
n = int(input("Enter a positive integer N: "))
total_sum = 0
current = 1

while current <= n:
    total_sum += current
    current += 1

print("Sum of numbers from 1 to", n, "is:", total_sum)
'''

# 2. For Loop & range() FE: Printing multiples and loop iteration
# Demonstrates for loop over a sequence generated by range(start, stop, step)
'''
print("Even numbers from 2 to 10:")
for num in range(2, 11, 2):
    print(num)
'''


# ==============================================================================
# STRING LOOPS & GUESS-AND-CHECK SEARCH
# ==============================================================================

# 3. String Loop FE: Counting character occurrences with a for loop
# (From Week 2 Course Material Exercise 3)
'''
my_string = input("Enter a sentence: ")
target_char = input("Enter a character to count: ")
count = 0

for letter in my_string:
    if letter.lower() == target_char.lower():
        count += 1

print(f"The character '{target_char}' appeared {count} time(s).")
'''

# 4. String Slicing Practice FE: Remove the nth character from a string
# (From Week 2 Course Material Exercise 1)
'''
test_string = "We want to remove the nth character from this string"
n = 8
# Slicing up to n-1 (excluding the nth char), then from n onward
new_string = test_string[:n-1] + test_string[n:]
print("Original:", test_string)
print("Modified:", new_string)
'''

# 5. Guess-and-Check (Exhaustive Enumeration) FE: Integer Square Root
# (From Week 2 Course Material)
x = int(input("Enter an integer to find its square root: "))
guess = 0

while guess**2 < abs(x):
    guess = guess + 1

if x < 0:
    print(x, "is negative, so it has no real square root.")
elif guess**2 == x:
    print("Square root of", x, "is", guess)
else:
    print(x, "is not a perfect square.")
